apiVersion: v1
kind: Service
metadata:
  name: estoque-front
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
  selector:
    app: estoque-front